export const measurements = [
    {
        id: 1,
        type: 'digitalStorage',
        label: 'Digital Storage',
        units: [
            {
                id: 11,
                unit: 'bytes',
                label: 'Bytes',
                short: 'B',
            },
            {
                id: 12,
                unit: 'kilobytes',
                label: 'Kilobytes',
                short: 'KB',
            },
            {
                id: 13,
                unit: 'megabytes',
                label: 'Megabytes',
                short: 'MB',
            },
            {
                id: 14,
                unit: 'gigabytes',
                label: 'Gigabytes',
                short: 'GB',
            },
            {
                id: 15,
                unit: 'terabytes',
                label: 'Terabytes',
                short: 'TB',
            },
        ],
    },
    {
        id: 2,
        type: 'length',
        label: 'Length',
        units: [
            {
                id: 21,
                unit: 'millimeters',
                label: 'Millimeters',
                short: 'mm',
            },
            {
                id: 22,
                unit: 'centimeters',
                label: 'Centimeters',
                short: 'cm',
            },
            {
                id: 23,
                unit: 'meters',
                label: 'Meters',
                short: 'm',
            },
            {
                id: 24,
                unit: 'kilometers',
                label: 'Kilometers',
                short: 'km',
            },
            {
                id: 25,
                unit: 'inches',
                label: 'Inches',
                short: 'in',
            },
            {
                id: 26,
                unit: 'feet',
                label: 'Feet',
                short: 'ft',
            },
            {
                id: 27,
                unit: 'yards',
                label: 'Yards',
                short: 'yd',
            },
            {
                id: 28,
                unit: 'miles',
                label: 'Miles',
                short: 'mi',
            },
        ],
    },
    {
        id: 3,
        type: 'volume',
        label: 'Volume',
        units: [
            {
                id: 31,
                unit: 'milliliters',
                label: 'Milliliters',
                short: 'mL',
            },
            {
                id: 32,
                unit: 'liters',
                label: 'Liters',
                short: 'L',
            },
            {
                id: 33,
                unit: 'US teaspoons',
                label: 'Teaspoons',
                short: 'tsp',
            },
            {
                id: 34,
                unit: 'US tablespoons',
                label: 'Tablespoons',
                short: 'tbsp',
            },
            {
                id: 35,
                unit: 'US fluid ounces',
                label: 'Ounces',
                short: 'oz',
            },
            {
                id: 36,
                unit: 'US legal cups',
                label: 'Cups',
                short: 'c',
            },
            {
                id: 37,
                unit: 'US liquid pints',
                label: 'Pints',
                short: 'p',
            },
            {
                id: 38,
                unit: 'US liquid quarts',
                label: 'Quarts',
                short: 'qt',
            },
            {
                id: 39,
                unit: 'US liquid gallons',
                label: 'Gallons',
                short: 'gal',
            },
        ],
    },
    {
        id: 4,
        type: 'temperature',
        label: 'Temperature',
        units: [
            {
                id: 41,
                unit: 'kelvin',
                label: 'Kelvin',
                short: 'K',
            },
            {
                id: 42,
                unit: 'fahrenheit',
                label: 'Fahrenheit',
                short: 'F',
            },
            {
                id: 43,
                unit: 'celsius',
                label: 'Celsius',
                short: 'C',
            },
        ],
    },
    {
        id: 5,
        type: 'time',
        label: 'Time',
        units: [
            {
                id: 51,
                unit: 'milliseconds',
                label: 'Milliseconds',
                short: 'ms',
            },
            {
                id: 52,
                unit: 'seconds',
                label: 'Seconds',
                short: 's',
            },
            {
                id: 53,
                unit: 'minutes',
                label: 'Minutes',
                short: 'min',
            },
            {
                id: 54,
                unit: 'hours',
                label: 'Hours',
                short: 'hr',
            },
            {
                id: 55,
                unit: 'days',
                label: 'Days',
                short: 'd',
            },
            {
                id: 56,
                unit: 'weeks',
                label: 'Weeks',
                short: 'wk',
            },
            {
                id: 57,
                unit: 'months',
                label: 'Months',
                short: 'mo',
            },
            {
                id: 58,
                unit: 'years',
                label: 'Years',
                short: 'yr',
            },
        ],
    },
    {
        id: 6,
        type: 'weight',
        label: 'Weight',
        units: [
            {
                id: 61,
                unit: 'milligrams',
                label: 'Milligrams',
                short: 'mg',
            },
            {
                id: 62,
                unit: 'grams',
                label: 'Grams',
                short: 'g',
            },
            {
                id: 63,
                unit: 'kilograms',
                label: 'Kilograms',
                short: 'kg',
            },
            {
                id: 64,
                unit: 'ounces',
                label: 'Ounces',
                short: 'oz',
            },
            {
                id: 65,
                unit: 'pounds',
                label: 'Pounds',
                short: 'lbs',
            },
            {
                id: 66,
                unit: 'US tons',
                label: 'Tons',
                short: 'ton',
            },
        ],
    },
]
