export const departments = [
    { id: 1, value: 'Academic Affairs' },
    { id: 2, value: 'Accounting, Business and Finance' },
    { id: 3, value: 'Admission' },
    { id: 4, value: 'Advancement' },
    { id: 5, value: 'Art and Art History' },
    { id: 6, value: 'Athletics' },
    { id: 7, value: 'Biology' },
    { id: 8, value: 'Bookstore' },
    { id: 9, value: 'Business Office' },
    { id: 10, value: 'Campus Ministry' },
    { id: 11, value: 'Campus Post Office' },
    { id: 12, value: 'Campus Safety' },
    { id: 13, value: 'Career Center' },
    { id: 14, value: 'Center for Community-Based Learning' },
    { id: 15, value: 'Chemistry' },
    { id: 16, value: 'Computer Science' },
    { id: 17, value: 'Dean of Students' },
    { id: 18, value: 'Division of Campus Life and Student Development' },
    { id: 19, value: 'Economics' },
    { id: 20, value: 'Education' },
    { id: 21, value: 'English' },
    { id: 22, value: 'Environmental Studies' },
    { id: 23, value: 'Facilities' },
    { id: 24, value: 'Financial Aid' },
    { id: 25, value: 'Government and International Affairs' },
    { id: 26, value: 'History' },
    { id: 27, value: 'Humanities' },
    { id: 28, value: 'Institutional Research' },
    { id: 29, value: 'International Programs' },
    { id: 30, value: 'Liberty Fellowship' },
    { id: 31, value: 'Library' },
    { id: 32, value: 'Lifelong Learning at Wofford' },
    { id: 33, value: 'Mathematics' },
    { id: 34, value: 'Military Science' },
    { id: 35, value: 'Modern Languages, Literatures and Cultures' },
    { id: 36, value: 'Music' },
    { id: 37, value: 'Office of Equity, Diversity and Inclusion' },
    { id: 38, value: 'Office of Marketing and Communications' },
    { id: 39, value: 'Office of the President' },
    { id: 40, value: 'Office of the Provost' },
    { id: 41, value: 'Office of the Registrar' },
    { id: 42, value: 'Philosophy' },
    { id: 43, value: 'Physical Education' },
    { id: 44, value: 'Physics' },
    { id: 45, value: 'Psychology' },
    { id: 46, value: 'Religion' },
    { id: 47, value: 'Residence Life' },
    { id: 48, value: 'Sociology and Anthropology' },
    { id: 49, value: 'Theatre' },
    { id: 50, value: 'Wellness Center' },
]
