export const departments = [
    'Academic Affairs',
    'Accounting, Business, and Finance',
    'Admission',
    'Advancement',
    'Art and Art History',
    'Athletics',
    'Biology',
    'Bookstore',
    'Business Office',
    'Campus Ministry',
    'Campus Post Office',
    'Campus Safety',
    'Career Center',
    'Center for Community-Based Learning',
    'Chemistry',
    'Computer Science',
    'Dean of Students',
    'Division of Campus Life and Student Development',
    'Economics',
    'Education',
    'English',
    'Environmental Studies',
    'Facilities',
    'Financial Aid',
    'Government and International Affairs',
    'History',
    'Humanities',
    'Institutional Research',
    'International Programs',
    'Liberty Fellowship',
    'Library',
    'Lifelong Learning at Wofford',
    'Mathematics',
    'Military Science',
    'Modern Languages, Literatures and Cultures',
    'Music',
    'Office of Equity, Diversity and Inclusion',
    'Office of Marketing and Communications',
    'Office of the President',
    'Office of the Provost',
    'Office of the Registrar',
    'Philosophy',
    'Physical Education',
    'Physics',
    'Psychology',
    'Religion',
    'Residence Life',
    'Sociology and Anthropology',
    'Theatre',
    'Wellness Center',
]
